#	$NetBSD: Makefile,v 1.10 2014/07/19 20:21:52 christos Exp $

.include "../Makefile.inc"

.PATH:		${S}/../external/mit/lua/dist/src \

KMOD=		luaproc
SRCS=		luaproc.c lpsched.c

WARNS=		0

CPPFLAGS+=	-I${S}/../external/mit/lua/dist/src \
		-I${S}/sys -DLUAPROC_USE_KTHREADS

.include <bsd.kmodule.mk>
